### ISSUE TITLE
Create SQLite databases for data pub

### ISSUE THREAD

**Issue by dlebauer** [terraref/terraref_data_paper#20]
* Seasons: 4&6
* Data Products:
  * Las plot clip
  * RGB plot clip 
  * Thermal plot clip (season 6 only)
* Changes to sample:
  * all climate variables should be trimmed to 4 significant digits 123.4 or 0.01234)
  * remove gene_markers table
  * add data products (I only see RGB)

if it would help you avoid moving data around,  you can run your scripts against the filesystem at workbench.terraref.org

TODO

* [x] Chris add code to data-publication repo
* [x] David review databases
* [ ] David document and upload to dryad submission

**Comment by Chris-Schnaufer** [comment]
@dlebauer Some questions and comments:
- ~Where can I find the date ranges for Seasons 4&6, or do I assume Jan 1 through Jun 30 2017/2018?~ Season 4 is 2017-04-13 to 2017-09-21 and Season 6 is 2018-04-20 to 2018-08-02
- For the dates in the DB you were looking at, RGB plot was the only sensor available
- I will look into workbench.terraref.org
- What's the date range you'd like to see in each database (minimum would be one per season)?

**Comment by dlebauer** [comment]
Seasons 

| Season | Planting Date | Harvest    |
|--------|---------------|------------|
| 4      | 2017-04-13    | 2017-09-21 |
| 6      | 2018-04-20    | 2018-08-02 |

These can be found at https://terraref.ncsa.illinois.edu/bety/api/v1/experiments?name=~Season+6 and https://terraref.ncsa.illinois.edu/bety/api/v1/experiments?name=~Season+4

re: splitting up the databases. I would split as little as possible.
* If you want to keep the size down, would it make sense to provide just a database with the 'unified' table? 
* if you want to improve performance, then does indexing take care of this? I suspect start_date, cultivar_name, plot_name, format, and sensor would be the most important fields to index.

**Comment by Chris-Schnaufer** [comment]
Indexing is very important for performance. The 'unified' table is a view and therefore prevents data duplication and keeps the size small. Making it a materialized view or as a single table would increase the size of the DB due to duplication.

**Comment by dlebauer** [comment]
@Chris-Schnaufer That makes sense - no need to worry about creating a materialized view - that is a pretty low priority.

**Comment by Chris-Schnaufer** [comment]
@dlebauer I'm not finding any masked plot level images to work with![Screen Shot 2020-04-30 at 11.54.55 AM.png](https://images.zenhubusercontent.com/5c14118eee1e975f1842e1c2/1fd16bf3-9954-4a3e-8540-3217d53eeb59)

**Comment by dlebauer** [comment]
you are correct that there are no plot level masks :-( I've updated the requirements

**Comment by Chris-Schnaufer** [comment]
I am not able to run this using Globus. It will always timeout before the run is complete. I'm waiting for the problems with workbench to be resolved via Rob Kooper or someone he sends me to

**Comment by Chris-Schnaufer** [comment]
Finishing this issue and writing a new ticket for remaining work that's dependent upon terraref workbench access

**Comment by Chris-Schnaufer** [comment]
https://app.zenhub.com/workspaces/ua-ag-data-science-5a57a3198339f11ba1c85775/issues/agpipeline/issues-and-projects/146

**Comment by dlebauer** [comment]
reopening - keeping as a placeholder for github.com/agpipeline/issues-and-projects/issues/146

**Comment by dlebauer** [comment]
@Chris-Schnaufer could you please check the code you used into https://github.com/terraref/data-publication/tree/master/code? (it doesn't have to be pretty, but hopefully commented so it could be used and adapted in the future)

**Comment by Chris-Schnaufer** [comment]
@dlebauer done: https://github.com/terraref/data-publication/tree/sqlite_jupyter_scripts

**Comment by dlebauer** [comment]
Remaining tasks are in https://github.com/az-digitalag/organization/issues/254
