### ISSUE TITLE
Create List of Data to be published

### ISSUE THREAD

**Issue by dlebauer** [terraref/terraref_data_paper#8]

**Comment by max-zilla** [comment]
(from our meeting notes on trip)

Seasons 4 & 6:
EnvironmentLogger netCDFs
Laser3D LAS files 
RGB GeoTIFFs & plot clips
Thermal IR GeoTIFFs & plot clips
PS2 PNGs
Field mosaics
Hyperspectral subset
BETY database dump (or potentially CSVs)
Source code for extractors (Zenodo DOIs)
Documentation
